# Site settings
title: Vidhub Blog
email: info@vidhub.co
description: "Video Review and Collaboration Made Simple"
baseurl: ""
url: "http://blog.vidhub.co"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

source: ./_source
destination: ./_site
